export const DATA = [
    {
        title: 'آپارتمان 120 متری',
        category: 'املاک ',
        image: "https://www.unsplash.it/136/136",
        price: '250$',
        Location: 'ولنجک',
        immadiate: false,
        shop: false,
        date: '5 ساعت قبل ',
        id: 1,

    },
    {
        title: 'ویلا 150 متری',
        category: 'املاک ',
        image: "https://www.unsplash.it/136/136",
        price: '5000$',
        Location: 'تهرانپارس',
        immadiate: false,
        shop: true,
        date: '7ساعت قبل ',
        id: 2,

    },
    {
        title: 'زمین 2000 متری',
        category: 'املاک ',
        image: '',
        price: '500$',
        Location: 'یوسف آباد',
        immadiate: true,
        shop: false,
        date: '2 ساعت قبل ',
        id: 3,

    },
    {
        title: 'دوخواب 120 متری',
        category: 'املاک ',
        image: '',
        price: '',
        Location: 'پردیس',
        immadiate: true,
        shop: true,
        date: '5 ساعت قبل ',
        id: 4,

    },
    {
        title: '3 طبقه ',
        category: 'املاک ',
        image: '',
        price: '7000$',
        Location: 'ایرانشهر',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 5,

    },
    {
        title: '206 صندوقدار',
        category: 'وسایل نقلیه ',
        image: "https://www.unsplash.it/136/136",
        price: '260$',
        Location: 'تجریش',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 6,

    },
    {
        title: 'تیگو 5',
        category: 'وسایل نقلیه ',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'سعادت آباد',
        immadiate: false,
        shop: true,
        date: 'احظاتی پیش ',
        id: 7,

    },
    {
        title: 'توسان 2012',
        category: 'وسایل نقلیه ',
        image: 'https://www.unsplash.it/136/136',
        price: '750$',
        Location: 'مرزداران',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 8,

    },
    {
        title: 'هیوندای اکسنت 2015',
        category: 'وسایل نقلیه ',
        image: 'https://www.unsplash.it/136/136',
        price: '860$',
        Location: 'نواب',
        immadiate: true,
        shop: false,
        date: ' 2 ساعت پیش ',
        id: 9,

    },
    {
        title: 'سوناتا 2016 ',
        category: 'وسایل نقلیه ',
        image: '',
        price: '',
        Location: 'میرداماد',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 10,

    },
    {
        title: ' ال ای دی  ',
        category: 'لوازام الکترونیکی  ',
        image: '',
        price: '560$',
        Location: 'میرداماد',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 11,

    },
    {
        title: '   پلی استیشن   ',
        category: 'لوازام الکترونیکی  ',
        image: 'https://www.unsplash.it/136/136',
        price: '720$',
        Location: 'سنگلچ',
        immadiate: false,
        shop: true,
        date: 'احظاتی پیش ',
        id: 12,

    },
    {
        title: ' لپ تاپ ایسوس  ',
        category: 'لوازام الکترونیکی  ',
        image: '',
        price: '750$',
        Location: 'میرداماد',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 13,

    },
    {
        title: 'مودم  ',
        category: 'لوازام الکترونیکی  ',
        image: '',
        price: '',
        Location: 'نیاوران',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 14,

    },
    {
        title: 'ps4',
        category: 'لوازام الکترونیکی  ',
        image: 'https://www.unsplash.it/136/136',
        price: '230$',
        Location: 'ورامین',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 15,

    },
    {
        title: 'فرش دستباف ',
        category: 'مربوط به خانه',
        image: '',
        price: '',
        Location: 'تهران نو',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 16,

    },
    {
        title: 'تشک طبی ',
        category: 'مربوط به خانه',
        image: 'https://www.unsplash.it/136/136',
        price: '260$',
        Location: 'نعمت آباد',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 17,

    },
    {
        title: 'لوستر مشکی ',
        category: 'مربوط به خانه ',
        image: 'https://www.unsplash.it/136/136',
        price: '500$',
        Location: 'افسریه ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 18,

    },
    {
        title: 'آرکوپال اصل ',
        category: 'مربوط به خانه ',
        image: 'https://www.unsplash.it/136/136',
        price: '500$',
        Location: 'جمهوری',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 19,

    },
    {
        title: 'تاب ریلکسی ',
        category: 'مربوط به خانه ',
        image: '',
        price: '72$',
        Location: 'اقدسیه',
        immadiate: true,
        shop: true,
        date: 'احظاتی پیش ',
        id: 20,

    },
    {
        title: 'سقف های کاذب ',
        category: 'خدمات ',
        image: 'https://www.unsplash.it/136/136',
        price: '50$',
        Location: 'آذری',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 21,

    },
    {
        title: 'کیک خانگی ',
        category: 'خدمات ',
        image: 'https://www.unsplash.it/136/136',
        price: '70$',
        Location: 'زعفرانیه',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 22,

    },
    {
        title: 'باربری ',
        category: 'خدمات ',
        image: 'https://www.unsplash.it/136/136',
        price: '20$',
        Location: 'تهرانسر',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 23,

    },
    {
        title: 'قالیشویی ',
        category: 'خدمات ',
        image: '',
        price: '12$',
        Location: 'آذری',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 24,

    },
    {
        title: 'خدمات تخصصی رنگ مو ',
        category: 'خدمات ',
        image: 'https://www.unsplash.it/136/136',
        price: '27$',
        Location: 'جنت آباد ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 25,

    },
    {
        title: 'نقاشی ساختمان ',
        category: 'خدمات ',
        image: '',
        price: '',
        Location: 'جنت آباد ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 26,

    },
    {
        title: 'کفش چرم طبیعی ',
        category: 'وسایل شخصی ',
        image: '',
        price: '43$',
        Location: 'مرزداران',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 27,

    },
    {
        title: 'کاپشن مدانه  ',
        category: 'وسایل شخصی ',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'الهیه ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 28,

    },
    {
        title: 'نیم بوت خز دار',
        category: 'وسایل شخصی ',
        image: '',
        price: '24$',
        Location: 'زعفرانیه',
        immadiate: false,
        shop: true,
        date: 'احظاتی پیش ',
        id: 29,

    },
    {
        title: 'تخت نوزاد',
        category: 'وسایل شخصی ',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'فاطمی',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 30,

    },
    {
        title: 'ساعت ',
        category: 'وسایل شخصی ',
        image: '',
        price: '36$',
        Location: 'مرزداران',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 31,

    },
    {
        title: 'دست بند زیبا ',
        category: 'وسایل شخصی ',
        image: 'https://www.unsplash.it/136/136',
        price: '20$',
        Location: 'استاد معین ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 32,

    },
    {
        title: 'بارانی زنانه ',
        category: 'وسایل شخصی ',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'آرژانتین',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 33,

    },
    {
        title: 'عروسک ',
        category: 'سرگرمی و فراغت ',
        image: '',
        price: '13$',
        Location: 'اکباتان ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 34,

    },
    {
        title: 'تور هوایی قشم',
        category: 'سرگرمی و فراغت ',
        image: 'https://www.unsplash.it/136/136',
        price: '24$',
        Location: 'چیتگر ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 35,

    },
    {
        title: 'دنبل 2 کیلویی',
        category: 'سرگرمی و فراغت ',
        image: 'https://www.unsplash.it/136/136',
        price: '10$',
        Location: 'پردیس ',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 36,

    },
    {
        title: 'پیانو یاماها  ',
        category: 'سرگرمی و فراغت ',
        image: '',
        price: '',
        Location: 'جمهوری ',
        immadiate: false,
        shop: true,
        date: 'احظاتی پیش ',
        id: 37,

    },
    {
        title: 'صندلی منشی',
        category: 'اجتماعی',
        image: 'https://www.unsplash.it/136/136',
        price: '10$',
        Location: 'آذربایجان ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 38,

    },
    {
        title: 'میز کارمندی',
        category: 'اجتماعی',
        image: '',
        price: '',
        Location: 'شهرک امید ',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 39,

    },
    {
        title: 'دستگاه پوز',
        category: 'اجتماعی ',
        image: 'https://www.unsplash.it/136/136',
        price: '20$',
        Location: 'تهرانپارس  ',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 40,

    },
    {
        title: 'مبل اداری ',
        category: 'اجتماعی ',
        image: '',
        price: '',
        Location: 'پونک ',
        immadiate: false,
        shop: true,
        date: 'احظاتی پیش ',
        id: 41,

    },
    {
        title: 'کانتر اداری',
        category: 'اجتماعی ',
        image: 'https://www.unsplash.it/136/136',
        price: '47$',
        Location: 'پاسداران ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 42,

    },
    {
        title: 'انواع تجهیزات آرایشگاهی',
        category: 'اجتماعی ',
        image: '',
        price: '',
        Location: 'سعادت آباد ',
        immadiate: false,
        shop: true,
        date: 'احظاتی پیش ',
        id: 43,

    },
    {
        title: 'انواع قفسه فروشگاهی و انباری',
        category: 'اجتماعی ',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'بومهن ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 44,

    },
    {
        title: 'پارتیشن اداری',
        category: 'برای کسب و کار  ',
        image: '',
        price: '100$',
        Location: 'سهروردی ',
        immadiate: false,
        shop: true,
        date: 'احظاتی پیش ',
        id: 45,

    },
    {
        title: 'دستگاه اسپرسو ساز',
        category: 'برای کسب و کار  ',
        image: 'https://www.unsplash.it/136/136',
        price: '20$',
        Location: 'سبلان ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 46,

    },
    {
        title: 'سشوار صنعتی',
        category: 'برای کسب و کار  ',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'میدان حر ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 47,

    },
    {
        title: 'ولید و فروش انواع لباس زنانه ',
        category: 'برای کسب و کار  ',
        image: '',
        price: '',
        Location: 'بازار  ',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 48,

    },
    {
        title: 'استخدام بازاریاب',
        category: 'استخدام و کار یابی',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'ُسهروردی',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 49,

    },
    {
        title: ' طراح ناخن ',
        category: 'استخدام و کار یابی',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'آجودانیه',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 50,

    },
    {
        title: ' آشپز ایرانی',
        category: 'استخدام و کار یابی',
        image: '',
        price: '',
        Location: 'تهرانپارس',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 51,

    },
    {
        title: 'پیک موتوری تمام وقت ',
        category: 'استخدام و کار یابی',
        image: '',
        price: '',
        Location: 'تجریش',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 52,

    },
    {
        title: 'مشاور مبتدی و حرفه ای ',
        category: 'استخدام و کار یابی',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'شهر قدس',
        immadiate: false,
        shop: false,
        date: 'احظاتی پیش ',
        id: 53,

    },
    {
        title: ' برنامه نویس وب ',
        category: 'استخدام و کار یابی',
        image: 'https://www.unsplash.it/136/136',
        price: '',
        Location: 'شهریار',
        immadiate: true,
        shop: false,
        date: 'احظاتی پیش ',
        id: 54,

    },
]